FROM ubuntu:22.04

RUN apt update -y
RUN apt install -y curl python3 python3-pip python3-setuptools python3-dev gunicorn 

RUN apt update

COPY requirements.txt requirements.txt
COPY api /opt/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

WORKDIR /opt/

EXPOSE 8000

CMD ["gunicorn","-b","0.0.0.0:8000","app:app","--workers=5","--threads=10","--timeout=1000","--log-level=debug"]
